#!/usr/bin/env bash
# guard-managed-files.sh — Warn when a canon-managed file is edited directly.
# PostToolUse[Edit|Write] hook. Feeds a warning back into context at the moment of the mistake.

INPUT=$(cat)
FILE=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('tool_input', {}).get('file_path', ''))
except Exception:
    pass
" 2>/dev/null)

[ -z "$FILE" ] && exit 0

case "$(basename "$FILE")" in
  CATALOG.md)
    echo ""
    echo "[canon] CATALOG.md is auto-generated by skills.sh — direct edits will be overwritten."
    echo "Update source files in skills/ instead, then run: skills.sh list"
    ;;
esac
